# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00f41cf54c53f97c9ce67099a124a5cc678fcdd057450570df8a4607ee669c51492d0b4dd3f040347e2e33bba5ea2413c30e0944b8fab3ae00cf23d6fe3cd9c4

test:
  secret_key_base: 500ccbb4c00d6c733940fe055a893b30aa27fbbd95585c674c108de9293b4b3a53192a1ea01ffce66fea3cef889adf70d1e36d55923a9ba0690ab212954180ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
